const LAB={"id":"supernova","title":"Supernova Hubble Diagram Lab","xLabel":"Redshift z","yLabel":"Distance modulus mu","controls":[["H0","H0 [km/s/Mpc]",70,60,78,0.1],["omegaM","Omega_m",0.3,0.15,0.45,0.005],["MBias","Magnitude offset",0,-0.4,0.4,0.01],["scatter","Intrinsic scatter",0.1,0.02,0.25,0.01]]};
const state={reference:null,params:Object.fromEntries(LAB.controls.map(c=>[c[0],c[2]])),result:null,worker:null,run:0,lastFrame:performance.now(),frames:0};
const $=id=>document.getElementById(id);
function fmt(v,d=3){return Number.isFinite(Number(v))?Number(v).toLocaleString('en-US',{maximumFractionDigits:d}):'--'}
function buildControls(){const root=$('controls');root.innerHTML='';for(const c of LAB.controls){const [key,label,value,min,max,step]=c;const wrap=document.createElement('label');wrap.innerHTML=`${label} <output id="out-${key}">${value}</output><input id="ctrl-${key}" type="range" min="${min}" max="${max}" step="${step}" value="${value}">`;root.appendChild(wrap);$('ctrl-'+key).addEventListener('input',e=>{state.params[key]=Number(e.target.value);$('out-'+key).textContent=e.target.value;runModel()})}}
async function loadReference(){const response=await fetch('data/reference.json',{cache:'no-cache'});if(!response.ok)throw Error('reference data HTTP '+response.status);state.reference=await response.json();$('referenceLabel').textContent=state.reference.dataset;$('notes').textContent=state.reference.source+'\n\n'+state.reference.citation}
function getWorker(){if(state.worker)return state.worker;state.worker=new Worker('physicsWorker.js');state.worker.onmessage=e=>{state.result=e.data;draw();renderMetrics();$('workerStatus').textContent='Worker ready'};state.worker.onerror=e=>{$('workerStatus').textContent='Worker error: '+e.message};return state.worker}
function runModel(){const worker=getWorker();state.run+=1;$('runId').textContent='run '+String(state.run).padStart(3,'0');worker.postMessage({lab:LAB.id,params:state.params,reference:state.reference})}
function bounds(series,points){const xs=[],ys=[];for(const s of series||[]){xs.push(...s.x);ys.push(...s.y)}for(const p of points||[]){xs.push(p.x);ys.push(p.y)}return{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)}}
function drawAxes(ctx,w,h,b){ctx.strokeStyle='rgba(148,163,184,.35)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(70,28);ctx.lineTo(70,h-58);ctx.lineTo(w-24,h-58);ctx.stroke();ctx.fillStyle='#8b93a3';ctx.font='12px Consolas, monospace';ctx.fillText(LAB.yLabel,18,22);ctx.fillText(LAB.xLabel,w-220,h-20);for(let i=0;i<=5;i++){const x=70+(w-100)*i/5,y=h-58-(h-90)*i/5;ctx.fillText(fmt(b.minX+(b.maxX-b.minX)*i/5,2),x-18,h-38);ctx.fillText(fmt(b.minY+(b.maxY-b.minY)*i/5,2),18,y+4);ctx.strokeStyle='rgba(148,163,184,.10)';ctx.beginPath();ctx.moveTo(x,28);ctx.lineTo(x,h-58);ctx.moveTo(70,y);ctx.lineTo(w-24,y);ctx.stroke()}}
function drawSeries(){const canvas=$('seriesCanvas'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const series=state.result?.series||[],points=state.reference?.points||[],b=bounds(series,points);const padY=(b.maxY-b.minY||1)*.12;b.minY-=padY;b.maxY+=padY;drawAxes(ctx,w,h,b);const sx=x=>70+(x-b.minX)/(b.maxX-b.minX||1)*(w-100),sy=y=>h-58-(y-b.minY)/(b.maxY-b.minY||1)*(h-90);
  // Pantheon+ points first (underneath the model curve), rendered as small markers with 1-sigma error bars
  const dense=points.length>40;
  for(const p of points){const x=sx(p.x),y=sy(p.y);
    if(p.y_err){const yTop=sy(p.y+p.y_err),yBot=sy(p.y-p.y_err);ctx.strokeStyle='rgba(255,209,102,.35)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x,yTop);ctx.lineTo(x,yBot);ctx.stroke()}
    ctx.fillStyle='#ffd166';ctx.beginPath();ctx.arc(x,y,dense?1.6:5,0,Math.PI*2);ctx.fill();
    if(!dense){ctx.strokeStyle='#14171d';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#eef1f6';ctx.fillText(p.label||'reference',x+8,y-8)}}
  if(dense){ctx.fillStyle='#ffd166';ctx.fillText(`${points.length} Pantheon+SH0ES supernovae (1-sigma error bars)`,90,h-64)}
  for(const s of series){ctx.strokeStyle=s.color||'#e0693f';ctx.lineWidth=2;ctx.beginPath();s.x.forEach((x,i)=>{const px=sx(x),py=sy(s.y[i]);if(i)ctx.lineTo(px,py);else ctx.moveTo(px,py)});ctx.stroke();ctx.fillStyle=s.color||'#e0693f';ctx.fillText(s.name,90,48+18*series.indexOf(s))}}
function drawResiduals(){const canvas=$('residCanvas');if(!canvas)return;const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const resid=state.result?.residuals||[];if(!resid.length)return;const xs=resid.map(r=>r.x),ys=resid.map(r=>r.y);const minX=Math.min(...xs),maxX=Math.max(...xs);const maxAbsY=Math.max(0.3,...ys.map(Math.abs));const sx=x=>50+(x-minX)/(maxX-minX||1)*(w-70),sy=y=>h/2-(y/maxAbsY)*(h/2-16);
  ctx.strokeStyle='rgba(148,163,184,.25)';ctx.beginPath();ctx.moveTo(50,h/2);ctx.lineTo(w-20,h/2);ctx.stroke();
  ctx.fillStyle='#8b93a3';ctx.font='11px Consolas, monospace';ctx.fillText('Δmu (model - Pantheon+) [mag]',50,14);ctx.fillText('z',w-24,h-4);
  for(const r of resid){const x=sx(r.x),y=sy(r.y);ctx.fillStyle=Math.abs(r.y)>0.3?'#ff6b6b':'#72f2a7';ctx.beginPath();ctx.arc(x,y,1.8,0,Math.PI*2);ctx.fill()}}
function drawHeatmap(){const canvas=$('heatCanvas'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;const m=state.result?.heatmap;if(!m)return;const img=ctx.createImageData(w,h);for(let y=0;y<h;y++){for(let x=0;x<w;x++){const ix=Math.floor(x/w*m.n),iy=Math.floor(y/h*m.n),v=m.values[iy*m.n+ix];const o=(y*w+x)*4;img.data[o]=Math.min(255,20+240*v);img.data[o+1]=Math.min(255,70+190*Math.sqrt(v));img.data[o+2]=Math.min(255,120+100*(1-v));img.data[o+3]=255}}ctx.putImageData(img,0,0);ctx.fillStyle='rgba(11,15,25,.78)';ctx.fillRect(12,12,260,54);ctx.fillStyle='#eef1f6';ctx.font='13px Consolas, monospace';ctx.fillText(m.label,24,44)}
function draw(){drawSeries();drawHeatmap();drawResiduals()}
function renderMetrics(){const root=$('metrics');root.innerHTML='';for(const [k,v] of Object.entries(state.result?.metrics||{})){const d=document.createElement('div');d.className='metric';d.innerHTML=`<span>${k}</span><strong>${fmt(v,4)}</strong>`;root.appendChild(d)}}
function tick(now){state.frames++;if(now-state.lastFrame>1000){$('frameRate').textContent=Math.round(state.frames*1000/(now-state.lastFrame))+' fps';state.frames=0;state.lastFrame=now}requestAnimationFrame(tick)}
$('reset').addEventListener('click',()=>{for(const c of LAB.controls){state.params[c[0]]=c[2];$('ctrl-'+c[0]).value=c[2];$('out-'+c[0]).textContent=c[2]}runModel()});
buildControls();loadReference().then(runModel).catch(err=>{$('workerStatus').textContent='Reference error';$('notes').textContent=err.message});requestAnimationFrame(tick);
